/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package authentication;

import javax.swing.JOptionPane;
//personal added imports here
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
/**
 *
 * @author franz
 */


public class Patient_Registration extends javax.swing.JInternalFrame {

    /**
     * Creates new form Patient_Registration
     */
    public Patient_Registration() {
        initComponents();
    }
    
    //Connection Db - DATABASE CONNECTION
    Connection con = connectionDB.getConnectionDB();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_patient = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(626, 517));

        add_patient.setText("Add Patient");
        add_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_patientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(add_patient)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(add_patient)
                .addContainerGap(421, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_patientActionPerformed
        // TODO add your handling code here:
        dispose();
        AddPatreg apr = new AddPatreg();
        apr.setVisible(true);
    }//GEN-LAST:event_add_patientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_patient;
    // End of variables declaration//GEN-END:variables
}
